{% set name = "extinction" %}
{% set version = "0.4.5" %}
{% set sha256 = "e6a90cf8c66cdb0cb747fb1114da4b959b95aa073db4919ad530aa844b8beb42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - extinction

about:
  home: http://github.com/kbarbary/extinction
  license: MIT
  license_file: LICENSE
  summary: Fast interstellar dust extinction laws
  description: |
    Cython-optimized implementations of empirical dust exitinction laws
    found in astronomy literature.
  dev_url: https://github.com/kbarbary/extinction
  doc_url: https://extinction.readthedocs.io

extra:
  recipe-maintainers:
    - kbarbary
    - guillochon
