{% set name = "extinction" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b2bd7cfd7b027de2bd18ed813235441ccbdd832f987928282714327c8d3aebb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - pip
    - cython
  run:
    - python

test:
  imports:
    - extinction

about:
  home: http://github.com/kbarbary/extinction
  license: MIT
  license_file: LICENSE
  summary: Fast interstellar dust extinction laws
  description: |
    Cython-optimized implementations of empirical dust exitinction laws
    found in astronomy literature.
  dev_url: https://github.com/kbarbary/extinction
  doc_url: https://extinction.readthedocs.io

extra:
  recipe-maintainers:
    - benjaminrose
    - kbarbary
    - guillochon
