{% set name = "extinction" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d16dec13a0404e04c3631f38628eb3b233ac07deac2950129dd136da8f7e4438

build:
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - extinction

about:
  home: http://github.com/kbarbary/extinction
  license: MIT
  license_file: LICENSE
  summary: Fast interstellar dust extinction laws
  description: |
    Cython-optimized implementations of empirical dust exitinction laws
    found in astronomy literature.
  dev_url: https://github.com/kbarbary/extinction
  doc_url: https://extinction.readthedocs.io

extra:
  recipe-maintainers:
    - benjaminrose
    - kbarbary
    - guillochon
