appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AaN3yVng4KNmU1Pw1VneJig9l42hx6hv1eKfFy6o7Xnz6RggjQ+2en/MyBtgLof25uhs36yzvqSshIs4CH31xTXMK0bGci2WyHaKyJd3gRyfoi1HDNV22B4SCGZBLoA5z4KxAAq1oiUKiBFk7lGGkMkL16a8w3Xv8ZsQ4EQuAihMlo3z89UwaxiZ7kqmvAOplwWflixr5NcPXeelY7yH59qQknZfuE1HMQje0YgvpHHMxArzDomwbAt65SdomVhU1rsA9I6xujxFAUfbFRunvtCSPN9fMJLjVh4YU4YUsuxTQ4qFiOQcy1GyqJ43tGhn5sxdgmGx0EOfoHw7Sk1YOjZZqvGLzcerAg4gRmlSGQkWqazgJPKF5vZ1A4pwGfImdoKCuALLzdOIQGN5Q+g+tN5kguTWPQN/BLkuZPcOCCO/4dd6hAgNwQt0Rv7SdRs3a/3ssK0VLgkXDRy1f5JFV0S25u5qHC2m1WzHgKyJDPQNYTV8nvVN2xNCkKi5CYzBnA2Ch9/jpk0dNqmi+VqenrQosmlNmc8AgEcQ8N7w6wsqR8KdDF7vX0wrRevXEbdDgi/xuhaCf293LJtlMz1YpLCqyuc73liK91qMhAhCjJ3TwrFkWFlRVP1JOtZsIC5EdaKFJiv+hV8osnAip4Kqp2mpeiXTZ7qVBpOl/LNZNeY=}
provider:
  win: azure
