travis:
  secure:
    BINSTAR_TOKEN: qhYz+PvfMaZHwC5SKYFjv9sCLdnSLRptikiLjw9O1oTxpCMeWeEzJsasuDWgJtasJ7CX0AU7ZiJx7EXbtlVLPiCUVnkB5mum2TQKvAKkOkjZXbBiSOTRPmWLCkHCXqHsN7a/TK1QIwt7YvAeO3FUM0dqwI6XYHVzZtNQULajKH06jHY0U8Z67zMy175lRuefFNyR/tvedjN0GXr4Gu4XWGmsi5cGuWTK9kAIt1SKrVDATtpug04x9djBX02wPh+mFNKguelCh2GeLZgoI+tzPUCbv79su/c3BK+e2qq0Wx1D2Jcrxu05eUiYC+xjX1CR9RTGiNPbGvKh2VzWKjKAu7KUsvdSPVHHWI2yEyvjNuj8A3R1ZDXZ8VXpssyz1HOHdUxVvP7CXXmtu78dUR76xS3bLhTFLXakMd132JAkxIhZFdCblb8Z6hxsQXUpVYSR/yp7ltWREuTrNyr5kNOdyk4FE+NBi6N23vX1+L1Q1uFv30v6AuGbTp7WSJYeEGH/9BXHnryfX/07hc0rwV6M/gI58Ya4Nt4O6KfV2Mq41ddfLTWPS2/WG/3/hoz/+4weoaF/AqRIqI2ZcdEexc5/7uJrGLfDK3wlOuzh2yx4rfk2yLGoIWdJNaU4a/iaNvB5ltaXky3daqnQgcg93aDexF9DjW1Sdn2NmEUHWwXKfFo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
